[package]
name = "color"
version = "0.1.0"
authors = ["gregory <10611760+gregoryguillou@users.noreply.github.com>"]
edition = "2018"

[dependencies]
warp = "0.3"
tokio = { version = "1.6.0", features = ["full"] }

